add_info/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.static import serve

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.index, name='index'),
                  url(r'^select_category$', views.add_info, name='new_info'),
                  url(r'^add_data/(?P<category_id>.*)/(?P<type>.*)$', views.add_data, name='add_data'),
                  url(r'^check_data/$', views.check_data, name='check_data'),
                  url(r'^added_succesfully/$', views.added_succesfully, name='added_succesfully'),
                  url(r'^profile/$', views.profile, name='profile'),
                  url(r'^user_info/$', views.user_info, name='user_info'),
                  url(r'^select_recommend/$', views.select_recommend, name='select_recommend'),
                  url(r'^list_of_rec/$', views.list_of_rec, name='list_of_rec')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diploma_recommend_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_info/', include('add_info.urls')),
]

add_info/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Role(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(default='', blank=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lastname = models.CharField(max_length=50, blank=True)
    firstname = models.CharField(max_length=50, blank=True)
    patronymic = models.CharField(max_length=50, blank=True)
    group = models.CharField(max_length=10, blank=True)
    role = models.ManyToManyField(Role, blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return "User - %s, фамилия - %s, имя - %s , отчетство - %s, группа - %s, роль - %s" \
               % (self.user, self.lastname, self.firstname, self.patronymic, self.group, self.role)

TYPE_OF_INPUT_INFO = (
    ('LT', 'Список значений'),
    ('UI', 'Ввод данных'),
    ('DC', 'Документ'),
    ('LK', 'Ссылка'),
    ('IM', 'Изображение'),
)

class InfoSource(models.Model):
    type = models.CharField(max_length=2, choices=TYPE_OF_INPUT_INFO, verbose_name='Тип загружаемых данных')
    createdUserRole = models.ManyToManyField(Role, verbose_name='Роль пользователя')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    itemNameKeywords = models.TextField(default='', verbose_name='Ключевые слова для поиска названия')
    existOfName = models.BooleanField(verbose_name='Наличие данных о пользователе')
    existOfScore = models.BooleanField(verbose_name='Наличие оценки')
    scoreDescription = models.TextField(default='', verbose_name='Описание')
    scoreKeywords = models.TextField(default='', verbose_name='Ключевые слова для поиска оценки')
    existOfDescription = models.BooleanField(verbose_name='Наличие описания')
    isRequiredDescription = models.BooleanField(verbose_name='Обязательность добавления описания')

    class Meta:
        verbose_name = "Категории"
        verbose_name_plural = 'Категория'

STATUS_OF_USER_ITEMS = (
    ('R', 'Recommendation'),
    ('U', 'UserInfo')
)

class UserItem(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)
    type = models.CharField(max_length=1, choices=STATUS_OF_USER_ITEMS)
    creaedDate = models.DateTimeField(auto_now=True)

class Photo(models.Model):
    file = models.ImageField(upload_to='images/', verbose_name='Файл для распознавания')
    file_cropped = models.ImageField(upload_to='images/', verbose_name='Файл для распознавания', blank=True, default='1')
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    userItem = models.ForeignKey(UserItem, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

class File(models.Model):
    file = models.FileField(upload_to='files/', verbose_name='Файл для распознавания')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    userItem = models.ForeignKey(UserItem, on_delete=models.CASCADE)
    startPage = models.IntegerField(blank=True)
    endPage = models.IntegerField(blank=True)

class Link(models.Model):
    name = models.TextField()
    userItem = models.ForeignKey(UserItem, on_delete=models.CASCADE)

add_info/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo

class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        cropped_image.save(photo.file.path)

        return photo.id

add_info/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .get_text.get_text_from_img import get_test_from_img as get_text
from .models import Photo
from .forms import PhotoForm

# Create your views here.
from django.urls import reverse
from nltk.inference.tableau import Categories

import add_info.models as m


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


def add_info(request):
    if request.method == 'POST':
        selectedCategory = m.Category.objects.get(name='Конкурсы').id
        selectedType = 'IM'
        return redirect(reverse('add_data', kwargs={'category_id': selectedCategory, 'type': selectedType}))
    else:
        categories = m.Category.objects.all()
        info_source_types = {}
        for elem in categories:
            types = m.InfoSource.objects.filter(category=elem).values_list("type", flat=True)
            info_source_types[elem] = types
        name_types = {}
        for elem in m.TYPE_OF_INPUT_INFO:
            name_types[elem[0]] = elem[1]
        return render(request, "add_info/add_new_info.html",
                      {'categories': categories, 'source_types': info_source_types, 'source_text': name_types})


def add_data(request, category_id, type):
    category = m.Category.objects.get(id=category_id)
    if type == 'IM':
        if request.method == 'POST':
            form = PhotoForm(request.POST, request.FILES)
            if form.is_valid():
                id = form.save()
                return redirect(reverse('check_data'))
        else:
            form = PhotoForm()
        return render(request, 'add_info/photo_list.html', {'form': form, 'category': category})


def check_data(request):
    if request.method == 'POST':
        return redirect(reverse('added_succesfully'))
    else:
        category = m.Category.objects.get(name='Олимпиады')
        print(category)
        # file = m.Photo.objects.get(id=file_id).file.url
        text = get_text('./media/images/83714980_68_page-0001.jpg')
        return render(request, 'add_info/check_data.html',
                      {'category': category, 'file': './media/images/83714980_68_page-0001.jpg', 'text': text})


def added_succesfully(request):
    return render(request, 'add_info/added_succesfully.html', {})


def profile(request):
    user = m.Profile.objects.get(id=1)
    return render(request, 'add_info/profile.html', {'user': user})


def user_info(request):
    list_of_items = m.UserItem.objects.filter(Q(author_id=1) | Q(type='U')).order_by('-creaedDate')[5:]
    return render(request, 'add_info/user_info.html', {'items': list_of_items})


def select_recommend(request):
    if request.method == "POST":
        return redirect(reverse('list_of_rec'))
    else:
        categories = m.Category.objects.all()
        items = m.Item.objects.filter(category__name='Курсы')
        return render(request, 'add_info/select_recommend.html', {'categories': categories, 'items': items})


def list_of_rec(request):
    category = m.Category.objects.get(name='Онлайн-курсы')
    method = "Рекомендации похожих элементов"
    list_rec = m.UserItem.objects.filter(Q(author_id=1) | Q(type='R') | Q(category=category)).order_by('-creaedDate')[:4]
    list_rec = reversed(list(list_rec))
    return render(request, 'add_info/list_of_rec.html', {'category': category, 'method': method, 'list_rec': list_rec})

templates/add_info/add_new_info.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <h1><b>Загрузка новых данных - Выбор категории</b></h1>
    <br>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 33%;"
             aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="100">
        </div>
    </div>
    <form name="form" enctype="multipart/form-data" action="{% url "new_info" %}" method="post">
        {% csrf_token %}
        <div class="col-md-6">
            <div class="form-group">
                <label for="categorySelect">Выберите категорию элемента</label>
                <select class="form-control" id="categorySelect" name="category">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="typeSelect">Выберите тип загружаемых данных</label>
                <div id="result"></div>
                <select class="form-control" id="typeSelect" name="category">
                    {% for value in source_types|get_value_from_dict:categories.2 %}
                        <option value="{{ value }}">{{ source_text|get_value_from_dict:value }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-offset-9 col-md-3">
                <button type="submit" href="" class="btn btn-primary labelText">
                    Далее
                </button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        {#function getValue() {#}
        {#    var select = document.getElementById("categorySelect");#}
        {#    var value = select.value;#}
        {#    alert(value);#}
        {##}
    </script>
{% endblock main %}

templates/add_info/added_succesfully.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Успешная загрузка{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <h1><b>Данные успешно сохранены!</b></h1>
        <button type="submit" href="" class="btn btn-primary labelText">
            Добавить еще результаты
        </button>
        <a type="submit" href="{% url "profile" %}" class="btn btn-primary labelText">
            Перейти в личный кабинет
        </a>
{% endblock %}

templates/add_info/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "css/bootstrap.min.css" %}" type="text/css" rel="stylesheet"/>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
    {% block staticfiles %}{% endblock %}
<body>
<div class="container main">
    <div class="page-header">
        <img src="{% static "/img/new_logo.png" %}" alt="Logo" class="img-responsive">
    </div>

    {% block main %}{% endblock %}
</div>
<div id="footer">
    <div class="container">
        <p class="text-muted">Разработка рекомендательной системы на основе сбора и анализа данных об образовательных
            результатах обучающихся</p>
    </div>
</div>
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/cropper.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/add_info/check_data.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <h1><b>Загрузка новых данных - Проверка</b></h1>
    <br>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 99%;"
             aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="100">
        </div>
    </div>
    <form name="form" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="col-md-6">
            <div class="form-group">
                <label for="category_name" class="labelText">Название категории</label>
                <input class="form-control" type="text" value="{{ category.name }}" readonly>
            </div>
            <div class="form-group">
                <label for="user_name" class="labelText">ФИО студента</label>
                <input class="form-control" type="text" value="Басаргина Светлана Юрьевна">
            </div>
            <div class="form-group">
                <label for="group" class="labelText">Группа</label>
                <input class="form-control" type="text">
            </div>
            <div class="form-group">
                <label for="category_name" class="labelText">Название элемента</label>
                <textarea class="form-control" type="text" rows="5">Всероссийской студенческой олимпиады &quot;Я—профессионал&quot; в 2018/2019 учебном году в категории &quot;Бакалавриат&quot;  по направлению &quot;Программная инженерия&quot;
                </textarea>
            </div>
            <div class="form-group">
                <label for="data" class="labelText">Дата</label>
                <input class="form-control" type="date" value="2018-01-01">
            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-12">
                <h3>Исходное изображение</h3>
                <img src={% static '/img/83714980_68_page-0001.jpg' %} id="image" style="max-width: 70%;">
            </div>
            <div class="col-md-12">
                <h3>Распознанный текст</h3>
                <div class="well well-small">
                    {{ text }}
                </div>
            </div>
        </div>
        <div class="col-md-offset-4 col-md-3">
            <button type="submit" href="" class="btn btn-primary labelText">
                Сохранить
            </button>
        </div>
    </form>
{% endblock %}

templates/add_info/list_of_rec.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url "profile" %}">Профиль</a></li>
            <li><a href="{% url 'user_info' %}">Мои результаты</a></li>
            <li class="active"><a href="{% url 'select_recommend' %}">Мои рекомендации</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <h1><b>Рекомендации</b></h1>
        <br>
        <h4><b>Категория: </b>{{ category.name }}</h4>
        <h4><b>Метод рекомендации: </b>{{ method }}</h4>
    </div>
    <div class="col-md-9 col-md-offset-3">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Приоритет</th>
                <th>Элемент</th>
                <th>Описание</th>
            </tr>
            </thead>
            <tbody>
            {% for item in list_rec %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.item }}</td>
                    <td><a href="">Подробнее...</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/add_info/photo_list.html
{% extends 'add_info/base.html' %}

{% block javascript %}
    <script>
        $(function () {

            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_file").change(function () {
                if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $("#image").attr("src", e.target.result);
                        $("#modalCrop").modal("show");
                    }
                    reader.readAsDataURL(this.files[0]);
                }
            });

            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
                $image.cropper({
                    viewMode: 1,
                    minCropBoxWidth: 200,
                    minCropBoxHeight: 200,
                    ready: function () {
                        $image.cropper("setCanvasData", canvasData);
                        $image.cropper("setCropBoxData", cropBoxData);
                    }
                });
            }).on("hidden.bs.modal", function () {
                cropBoxData = $image.cropper("getCropBoxData");
                canvasData = $image.cropper("getCanvasData");
                $image.cropper("destroy");
            });

            $(".js-zoom-in").click(function () {
                $image.cropper("zoom", 0.1);
            });

            $(".js-zoom-out").click(function () {
                $image.cropper("zoom", -0.1);
            });

            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function () {
                var cropData = $image.cropper("getData");
                $("#id_x").val(cropData["x"]);
                $("#id_y").val(cropData["y"]);
                $("#id_height").val(cropData["height"]);
                $("#id_width").val(cropData["width"]);
                $("#formUpload").submit();
            });

        });
    </script>
{% endblock %}

{% block main %}
    <h1><b>Загрузка новых данных - Выбор изображения</b></h1>
    <br>
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 66%;"
             aria-valuenow="33" aria-valuemin="0"
             aria-valuemax="100">
        </div>
    </div>
    <!-- FORM TO UPLOAD THE IMAGES -->
    <form method="post" enctype="multipart/form-data" id="formUpload">
        {% csrf_token %}
        <div class="form-group">
            <label for="category_name" class="labelText">Название категории</label>
            <input class="form-control" type="text" placeholder="{{ category.name }}" readonly>
        </div>
        <div class="form-group">
            <label class="labelText">Описание категории</label>
            <p>{{ category.description }}</p>
        </div>
        {{ form }}
    </form>

    <!-- MODAL TO CROP THE IMAGE -->
    <div class="modal fade" id="modalCrop">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Выделите фрагмент для распознавания</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="image" style="max-width: 100%;">
                </div>
                <div class="modal-footer">
                    <div class="btn-group pull-left" role="group">
                        <button type="button" class="btn btn-default js-zoom-in">
                            Zoom +
                        </button>
                        <button type="button" class="btn btn-default js-zoom-out">
                            Zoom -
                        </button>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-primary js-crop-and-upload">Распознать изображение</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/add_info/profile.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="{% url "profile" %}">Профиль</a></li>
            <li><a href="{% url 'user_info' %}">Мои результаты</a></li>
            <li><a href="{% url 'select_recommend' %}">Мои рекомендации</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <h1><b>{{ user.lastname }} {{ user.firstname }} {{ user.patronymic }}</b></h1>
        <br>
        <h4><b>Логин: </b>{{ user.user }}</h4>
        <h4><b>Группа: </b>{{ user.group }}</h4>
        <h4><b>Роль: </b>Студент</h4>
        <div class="col-md-offset-10 col-md-2">
            <button type="button" class="btn btn-default btn-lg">
                Изменить данные
            </button>
        </div>
    </div>


{% endblock %}

templates/add_info/select_recommend.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url "profile" %}">Профиль</a></li>
            <li><a href="{% url 'user_info' %}">Мои результаты</a></li>
            <li class="active"><a href="{% url 'select_recommend' %}">Мои рекомендации</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <h1><b>Получить рекомендации</b></h1>
        <br>
        <form name="form" enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="categorySelect">Выберите категорию элемента</label>
                <select class="form-control" id="categorySelect" name="category">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="categorySelect">Выберите тип рекомендации</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1" data-placement="right"
                           title="Предлагает рекомендации элементов выбранной категории">
                        Рекомендации внутри категории
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault2" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1" data-placement="right"
                           title="Предлагает рекомендации элементов, которые не совпадают с выбранной категорией, но выбирались в то же время что и заданный элемент">
                        Рекомендации сопутствующих элементов
                    </label>
                </div>
                <div class="form-check">
                    <input checked class="form-check-input" type="radio" name="flexRadioDefault1" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1" data-placement="right"
                           title="Предлагает рекомендации элементов других категорий, содержание которых совпадает с заданным элементом">
                        Рекомендации похожих элементов
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="flexRadioDefault3" id="flexRadioDefault1">
                    <label class="form-check-label" for="flexRadioDefault1" data-placement="right"
                           title="Предлагаетнесколько один или несколько элементов что нужно изучить до заданного элемента">
                        Цепочка рекомендаций
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label for="categorySelect">Выберите элемент</label>
                <select class="form-control" id="categorySelect" name="category">
                    {% for category in items %}
                        <option value="{{ category.id }}">{{ category }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md-offset-8 col-md-3">
                <button type="submit" href="" class="btn btn-primary labelText">
                    Получить рекомендации
                </button>
            </div>
        </form>
    </div>
{% endblock %}

templates/add_info/user_info.html
{% extends 'add_info/base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Загрузка данных{% endblock title %}

{% block staticfiles %}
    <link href="{% static "css/distribution.css" %}" rel="stylesheet">
{% endblock staticfiles %}

{% block main %}
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="{% url "profile" %}">Профиль</a></li>
            <li class="active"><a href="{% url 'user_info' %}">Мои результаты</a></li>
            <li><a href="{% url 'select_recommend' %}">Мои рекомендации</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="col-md-9">
            <h1><b>Результаты</b></h1>
        </div>
        <div class="col-md-3">
            <a type="submit" href="{% url "new_info" %}" class="btn btn-primary labelText">
                Загрузить данные
            </a>
        </div>
        <br>
        <div class="col-md-12">
            <input class="form-control" id="myInput" type="text" placeholder="Поиск..">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Элемент</th>
                    <th>Оценка</th>
                    <th>Категория</th>
                </tr>
                </thead>
                <tbody>
                {% for item in items %}
                    <tr>
                        <td>{{ item.item.name }}</td>
                        <td>{{ item.score }}</td>
                        <td>{{ item.category.name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}